[package]
name = "rust_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.13"
sdl2 = "0.25.0"
sdl2_image = "0.25.0"
sdl2_ttf = "0.25.1"
